### ISSUE TITLE
Can't start strapi after configuring apollo sandbox plugin

### ISSUE THREAD

**Issue by darkodavidovic** [creazy231/strapi-plugin-apollo-sandbox#6]
Strapi Version:   4.12.1 (node v18.17.1)   
 installed using: npm install @creazy231/strapi-plugin-apollo-sandbox --save
followed docs on: https://market.strapi.io/plugins/@creazy231-strapi-plugin-apollo-sandbox
done: npm run build --clean
Configured security middleware as in docs.
Configured plugins as: 
 {
 graphql: {
    config: {
      endpoint: '/graphql',
      shadowCRUD: true,
      playgroundAlways: true,
      defaultLimit: 100,
      maxLimit: 100,
      depthLimit: 100,
      amountLimit: 100,
      apolloServer: {
        tracing: false,
        introspection: true,
        cors: {
          credentials: true,
          methods: ['*'],
          origin: ['*'],
          headers: ['*']
        },
      },
    },
  },
  "apollo-sandbox": {
    enabled: true
  }
}
  The error on strapi startup:
  [1] [2023-09-08 12:51:54.587] debug: ⛔️ Server wasn't able to start properly.
[1] [2023-09-08 12:51:54.589] error: Error loading the plugin apollo-sandbox because apollo-sandbox is not installed. Please either install the plugin or remove it's configuration.
[1] Error: Error loading the plugin apollo-sandbox because apollo-sandbox is not installed. Please either install the plugin or remove it's configuration.
[1]     at Object.loadPlugins (/app/backend/node_modules/@strapi/strapi/lib/core/loaders/plugins/index.js:93:13)
[1]     at async Strapi.loadPlugins (/app/backend/node_modules/@strapi/strapi/lib/Strapi.js:346:5)
[1]     at async Promise.all (index 2)
[1]     at async Strapi.register (/app/backend/node_modules/@strapi/strapi/lib/Strapi.js:382:5)
[1]     at async Strapi.load (/app/backend/node_modules/@strapi/strapi/lib/Strapi.js:492:5)
[1]     at async Strapi.start (/app/backend/node_modules/@strapi/strapi/lib/Strapi.js:218:9)
[1] cd backend && npm run start exited with code 1

**Comment by creazy231** [comment]
did you also install the default strapi plugin for graphql?

**Comment by darkodavidovic** [comment]
> did you also install the default strapi plugin for graphql?

Yes. GraphQL works, and Apollo Sandbox works from manager only in development mode on localhost but without any config in plugins. Once i place apollo-sandbox plugin settins, strapi crashes. In production doesnt works because we have ip on the server, not a domain, vpn need to be enabled and also ssl certs are not enabled, so the tunnel cant be created brobably because of that.

**Comment by creazy231** [comment]
The Apollo Sandbox plugin is not designed to run in production since the default graphql strapi plugin playground is also not exposed in production by default.
Will try to reproduce the issue you're facing by also try to run it in production and will come back to you asap - hopefully with a fix :)

**Comment by darkodavidovic** [comment]
> The Apollo Sandbox plugin is not designed to run in production since the default graphql strapi plugin playground is also not exposed in production by default. Will try to reproduce the issue you're facing by also try to run it in production and will come back to you asap - hopefully with a fix :)

Mine is enabled in production, just plugins config does not accepting "apollo-sandbox" key in a config complaining that apollo-sanbox not installed. More over that, the main problem is non https conection and my closed network not allowing communication without vpn.
